"use client";

import { useState } from "react";
import type { RiskAssessment } from "@/lib/types";

interface DoctorCardProps {
  result: RiskAssessment;
}

function buildDoctorSummary(result: RiskAssessment): string {
  const lines: string[] = [];

  lines.push("AYURV HERB SAFETY SUMMARY");
  lines.push("(for discussion with healthcare provider)");
  lines.push("─".repeat(40));

  // blocked herbs
  if (result.blocked_herbs.length > 0) {
    lines.push("");
    lines.push(`BLOCKED (${result.blocked_herbs.length}):`);
    for (const herb of result.blocked_herbs) {
      const trigger =
        herb.trigger_type === "medication"
          ? `Drug interaction: ${herb.trigger}`
          : herb.trigger_type === "pregnancy"
            ? `Pregnancy/reproductive: ${herb.trigger}`
            : `Condition: ${herb.trigger}`;
      lines.push(`  • ${herb.herb_name} — ${trigger}`);
      lines.push(`    Reason: ${herb.reason}`);
    }
  }

  // medication interactions from caution herbs
  const medInteractions: string[] = [];
  for (const herb of result.caution_herbs) {
    for (const caution of herb.cautions) {
      if (caution.type === "medication_interaction") {
        const severity = caution.severity
          ? ` [${caution.severity.replace(/_/g, " ")}]`
          : "";
        medInteractions.push(
          `  • ${herb.herb_name} × ${caution.trigger}${severity}`
        );
        medInteractions.push(`    ${caution.explanation}`);
        if (caution.clinical_action) {
          medInteractions.push(`    Action: ${caution.clinical_action}`);
        }
      }
    }
  }

  if (medInteractions.length > 0) {
    lines.push("");
    lines.push("HERB-DRUG INTERACTIONS:");
    lines.push(...medInteractions);
  }

  // other cautions
  const otherCautions: string[] = [];
  for (const herb of result.caution_herbs) {
    for (const caution of herb.cautions) {
      if (caution.type !== "medication_interaction") {
        otherCautions.push(`  • ${herb.herb_name}: ${caution.explanation}`);
      }
    }
  }

  if (otherCautions.length > 0) {
    lines.push("");
    lines.push("OTHER CAUTIONS:");
    lines.push(...otherCautions);
  }

  // safe herbs
  if (result.safe_herbs.length > 0) {
    lines.push("");
    lines.push(`LOWER RISK (${result.safe_herbs.length}):`);
    for (const herb of result.safe_herbs) {
      const grade = herb.evidence_grade
        ? ` [Grade ${herb.evidence_grade}]`
        : "";
      lines.push(`  • ${herb.herb_name}${grade}`);
    }
  }

  lines.push("");
  lines.push("─".repeat(40));
  lines.push("Generated by Ayurv — Herb Safety Intelligence");
  lines.push("This is not a prescription. For discussion only.");

  return lines.join("\n");
}

export default function DoctorCard({ result }: DoctorCardProps) {
  const [copied, setCopied] = useState(false);
  const summaryText = buildDoctorSummary(result);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = summaryText;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  return (
    <div className="bg-gray-50 border border-gray-300 rounded-lg p-5 mb-8">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-semibold text-gray-800 text-sm flex items-center gap-2">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="w-5 h-5 text-ayurv-primary"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z"
            />
          </svg>
          Show My Doctor
        </h3>
        <button
          onClick={handleCopy}
          className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors ${
            copied
              ? "bg-risk-green text-white"
              : "bg-ayurv-primary text-white hover:bg-ayurv-secondary"
          }`}
        >
          {copied ? "Copied!" : "Copy Summary"}
        </button>
      </div>
      <p className="text-xs text-gray-500 mb-3">
        Copy this clinical summary to share with your doctor. It includes all
        blocked herbs, drug interactions, and cautions from your assessment.
      </p>
      <pre className="bg-white border border-gray-200 rounded p-3 text-xs text-gray-700 font-mono whitespace-pre-wrap overflow-x-auto max-h-48 overflow-y-auto">
        {summaryText}
      </pre>
    </div>
  );
}
